# Generated by Django 5.1.4 on 2025-03-16 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_studentsaf_regno'),
        ('manager', '0002_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsaf',
            name='presentEduSession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_year', to='manager.year'),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
