# Generated by Django 5.1.4 on 2025-03-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name_bn', models.CharField(blank=True, max_length=155, null=True)),
                ('institute_logo', models.ImageField(blank=True, null=True, upload_to='institute_logos/')),
                ('institute_address_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contact_number_1', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number_2', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
